### ISSUE TITLE
Same repo for hyper-flux-16step and hyper-flux-8step

### ISSUE THREAD

**Issue by sitatec** [lucataco/cog-hyper-flux-8step#1]
Hi @lucataco, Thanks for porting these to cog.

I noticed that you are using the same repo and weights for `hyper-flux-8step` and `hyper-flux-16step`. Is this intentional?
There seems to be 2 different weights on the ByteDance's HF repo, 1 for 8 steps and another for 16 steps.

**Comment by lucataco** [comment]
Yes, this is intentional. Both models share the underlying inference code, the only difference is the MODEL_URL, which would point to the 16step weights. (And of course, the default num_inference_steps is bumped to 16 for the 16step variant.)
